externalDatabase:
  host: milk-db.cximw24o4s0e.ap-south-1.rds.amazonaws.com
  port: 3306
  database: mpps
redis:
  image: redis:7-alpine
  port: 6379
  host: redis
backend:
  image:
    repository: vasu049/dairy-flow-backend
    tag: v1.0.31
  port: 8080
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"
jwt:
  secret: fgsdfg45sg8srgefyuegf7b548h516aret4hd6f6sg461gfhdf
  expiration: "86400000"
frontend:
  image:
    repository: vasu049/dairy-flow-frontend
    tag: v1.0.31
  port: 80
ingress:
  enabled: true
