---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-db-secret
  namespace: milk
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgCRQnXx9LkFmanQxcDaH3pIDtQYVMmv1m9wVbkJFD5Tu4NYDxaSz9wbzcotbqVhSG8U7fWE5GeXqamsP6CwwJnuy8WL2dvJ8U1ffEvBkrx0HV/U+ia6CF+tsZRD0mRitBg9KkzyONemt8tcnYqpuJX3oTpETLd3FTAikObpbUOV7EHwZ40XKHtI1L8GdXiKe/BASBJFNOzGeZ6S5kDnfcE33YmNeBTbjg1/zDQVuKRlXLaV58Feq2Pl48V/jGmqG4Hyi1dLqlstwK7ASwXxE7OcmzPOxfEZfntv9fnNAus9STmARIRcE8vejIpp/BU04msGK7lVz0PJaUJJtJn664Lqi69oebGyZ/tveZejn5ij++ssrNbF9pGONOLDVtZqHB0l9wITUTaOKF/fXfjxb/jOtHfXmkNZJFQRBsNjP3i0Or/uhyqSTZoRrglEStE1Of8A2C3GH2Um2KFo+TyPvJD1mwIiUSpXTzQEUNa62/kBC1Mw8c6sAlkMEGNsQPKg+g7JsQZJxKyYS1NEWdyK2tkgXOHigEKqPVgSSjBB1ekpjS1gE9kWbPIH/0kY3IReuqxXFMKh7Xq5iUA6vAW0Q86BwK0lioVwxGZ0qivvuf2mDSn+DbMBXyA2xh5LY6QOnpeCgCrETuh1Zcn2cMI1pESgnzFiydseUY8SdsfhAQgodNefKa4Wi/aUVtkX4P6Q4+WlO1RD5RpWQg==
    SPRING_DATASOURCE_USERNAME: AgCU23GdHR6xC88KXw9/n+/C+5VBfC/1kHPlJSbYS8yIxeZYaflxcHvbuHnJVJcmz+inza/BabLP3KBwrurDj9Rn+Ih9swt02JsCsVw8eMHQbWsisT2Wf9ruk/2W7/rrnWL0H95RAPiQL60l4sgBJxNJlJ2mVJCsPUkvNOVrWt7X7wwYff8W/pKW6iDXFX6sEboWLBazAGolscDqYLV7cYpkgpiYHFd1Fbn4+CUNxS2gvSVLBXmFHaGnRBvzS74ybIRL+T3ULOPpPInDXKI8ZNi+WYKVMWYuG90owj4HtbgPNKro9j4GG0lf00UeThxHNoIME0ldaqrkwL/xbqStj1OhbrfxJ4sNe4q8jk0+ixarr6i7Cx3Pr4Q6DJg6vZiQkWrdJCYifGAIFgoZRM0p+FJ3k9UEr8b87Eri6ifp6xjkD8lZc0thrRR97+unBpHcFh0iK7f3/RNx4CeUJfByQfGC9I/D9qjKwSOPQFIcvfz+lmxOU9XyDwQ4jjfoeMjq+dsUu0NLmQTcflGCpI/mrI64ohpxp5Wmn1z1TjYJl2nYYr3JfqA3xDie24Zi5GRXyiLbilJB0d36YVhzpg+4ZDjsuwSbA53G/ONaO7wtyQuDnu7PoAOBSg2Fls2niUUMU08GyNQ2K9d4TslrQzBWwUG4utCObKj9itRg5RNVbONjt/EraL61azSTPovdqLU/1QloGohbiQ==
  template:
    metadata:
      creationTimestamp: null
      name: backend-db-secret
      namespace: milk
    type: Opaque
